### ISSUE TITLE
Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://ruby.taobao.org/

### ISSUE THREAD

**Issue by ramzieus** [doabit/searchkick_demo#2]
Could not verify the SSL certificate for https://ruby.taobao.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed
for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your
Gemfile sources and change 'https' to 'http'.

**Comment by doabit** [comment]
The demo is too old, if you want to use it, replace `source 'https://ruby.taobao.org'` as `source 'https://rubygems.org'` in Gemfile.

**Comment by ramzieus** [comment]
Yeah I notice that it not work even I replace the source, Thank you @doabit .
